name: Auto Merge PR to master

on:
  push:
    branches:
      - test-pramod  # Trigger the workflow when 'test-pramod' branch is updated

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}  # Use a GitHub Personal Access Token (PAT) for authentication

      - name: Set up Git
        run: |
          git config --global user.name "pramod8959"
          git config --global user.email "pramoddewangan128@gmail.com"  # Replace with your email

      - name: Merge test-pramod into master
        run: |
          git checkout master || git checkout -b master origin/master
          git pull origin master
          git merge test-pramod --no-ff
          git push origin master
