name: Auto Merge PR to master

on:
  push:
    branches:
      - test-pramod  # This runs the workflow when the 'test-pramod' branch is updated

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Git
        run: |
          git config --global user.name "pramod8959"
          git config --global user.email "${{ secrets.GH_PAT }}"

      - name: Merge test-pramod into master
        run: |
          git fetch origin
          git checkout master
          git pull origin master
          git merge --no-ff test-pramod -m "Automated merge of test-pramod into master"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/pramod8959/testing_data.git main
